name: flyctl deploy
on: 
  push:
  schedule:
    - cron: '0 8 4 * *'
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  APP_NAME: ${{ secrets.APP_NAME }}
  SQLUSER: ${{ secrets.SQLUSER }}
  DATABASE: ${{ secrets.DATABASE }}
  SQLPASSWORD: ${{ secrets.SQLPASSWORD }}
  SQLHOST: ${{ secrets.SQLHOST }}
  SQLPORT: ${{ secrets.SQLPORT }}
  SQLNAME: ${{ secrets.SQLNAME }}
  FLYCTL_INSTALL: /usr/local
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up flyctl PATH
        run: |
          echo "export PATH=\"\$FLYCTL_INSTALL/bin:\$PATH\"" >> $HOME/.bashrc
          source $HOME/.bashrc
      - name: Print PATH
        run: echo "PATH: $PATH"
      - name: Install flyctl
        run: |
          sh -c "$(curl -L https://fly.io/install.sh)"
      - name: Verify flyctl installation
        run: flyctl version
      - name: Deploy
        run: |
          sh ./deploy.sh
