name: flyctl deploy
on: 
  push:
  schedule:
    - cron: '0 8 4 * *'
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  APP_NAME: ${{ secrets.APP_NAME }}
  SQLUSER: ${{ secrets.SQLUSER }}
  DATABASE: ${{ secrets.DATABASE }}
  SQLPASSWORD: ${{ secrets.SQLPASSWORD }}
  SQLHOST: ${{ secrets.SQLHOST }}
  SQLPORT: ${{ secrets.SQLPORT }}
  SQLNAME: ${{ secrets.SQLNAME }}
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Print PATH
        run: |
          echo "Original PATH: $PATH"
          echo "Contents of /usr/local/bin:"
          ls -la /usr/local/bin
          echo "Contents of /usr/bin:"
          ls -la /usr/bin
      - name: Deploy
        run: |
          export PATH="$PATH:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin:/usr/local/share"
          echo "Updated PATH: $PATH"
          sh ./deploy.sh
