name: flyctl deploy
on: 
  push:
  schedule:
    - cron: '0 8 4 * *'
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  APP_NAME: ${{ secrets.APP_NAME }}
  SQLUSER: ${{ secrets.SQLUSER }}
  DATABASE: ${{ secrets.DATABASE }}
  SQLPASSWORD: ${{ secrets.SQLPASSWORD }}
  SQLHOST: ${{ secrets.SQLHOST }}
  SQLPORT: ${{ secrets.SQLPORT }}
  SQLNAME: ${{ secrets.SQLNAME }}
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install flyctl
        run: |
          curl -L https://fly.io/install.sh | sh
          export FLYCTL_INSTALL="$HOME/.fly"
          export PATH="$FLYCTL_INSTALL/bin:$PATH"
          flyctl version  # Add this line to verify installation
      - name: Verify flyctl installation
        run: |
          echo "PATH: $PATH"
          ls -la $FLYCTL_INSTALL/bin
      - name: Deploy
        run: |
          sh ./deploy.sh
